ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.plural(/$/, 's')
  inflect.plural(/([^aeéiou])$/i, '\1es')
  inflect.plural(/([aeiou]s)$/i, '\1')
  inflect.plural(/z$/i, 'ces')
  inflect.plural(/á([sn])$/i, 'a\1es')
  inflect.plural(/é([sn])$/i, 'e\1es')
  inflect.plural(/í([sn])$/i, 'i\1es')
  inflect.plural(/ó([sn])$/i, 'o\1es')
  inflect.plural(/ú([sn])$/i, 'u\1es')

  inflect.singular(/s$/, '')
  inflect.singular(/es$/, '')

  inflect.irregular('el', 'los')
  inflect.irregular('user', 'users')
  inflect.irregular('persona', 'personas')
  inflect.irregular('modulo', 'modulos')
  inflect.irregular('personasoblrecibo','personasoblrecibos')
  inflect.irregular('paymentez', 'paymentez')
  inflect.irregular('planesrecaudosdetalle', 'planesrecaudosdetalles')
  inflect.irregular('planesrecaudo', 'planesrecaudos')
  inflect.irregular('epayco', 'epayco')
  inflect.irregular('infgrupo', 'infgrupos')
  inflect.irregular('infgruposcampo', 'infgruposcampos')
  inflect.irregular('migracioneslink', 'migracioneslinks')
  inflect.irregular('moduloscampo', 'moduloscampos')
  inflect.irregular('archivo', 'archivos')
  inflect.irregular('ejecucion', 'ejecuciones')
  #inflect.irregular('archivo', 'archivos')
  #inflect.irregular('archivo', 'archivos')
  #inflect.irregular('archivo', 'archivos')
  #inflect.irregular('archivo', 'archivos')

end
